name: Ⓜ️ New Milestone
description: Creates an issue to aggregate all features for a current milestone (each feature with its respective task issues).
title: "Ⓜ️ [MILESTONE]: "
labels: [enhancement, milestone]
body:
  - type: input
    id: start-date
    attributes:
      label: Start Date
      description: Enter the milestone start date (YYYY-MM-DD). Leave empty to use the creation date.
      placeholder: "YYYY-MM-DD (e.g., 2026-03-20)"
    validations:
      required: false

  - type: input
    id: end-date
    attributes:
      label: Target Completion Date
      description: Enter the estimated completion date for this milestone (YYYY-MM-DD).
      placeholder: "YYYY-MM-DD (e.g., 2026-04-20)"
    validations:
      required: false
  
  - type: textarea
    id: deliverables
    attributes:
      label: README
      description: README of this milestone.
      placeholder: |
        # v0.1.0 <RELEASE_NAME>
        ...
    validations:
      required: true

