<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>eb9626bc-787d-468c-a2c8-9562c3e83ea2</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engin3D.Storage.Composition\Engin3D.Storage.Composition.csproj" />
    <ProjectReference Include="..\Engin3D.Storage.Application\Engin3D.Storage.Application.csproj" />
  </ItemGroup>


  <ItemGroup>
    <Using Include="Engin3D.Storage.Composition.Extensions" />
    <Using Include="Microsoft.AspNetCore.Http" />
    <Using Include="Microsoft.AspNetCore.Mvc" />
  </ItemGroup>
</Project>
